import { useState, useCallback, useRef, useEffect } from "react";
import { Mail, FileText, BarChart3, Palette, Download, Send, Check, Image, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import * as XLSX from "xlsx";
import type { ProjectSummaryResponse } from "../../lib/collectorApi";
import type { Project } from "../../lib/projectApi";

interface Props {
  summary: ProjectSummaryResponse | null;
  project: Project | null;
  loading: boolean;
  activeReport: "email-reports" | "pdf-report" | "excel-export" | "infographic";
}

function platformLabel(p: string) {
  const map: Record<string, string> = { twitter: "Twitter", reddit: "Reddit", youtube: "YouTube", medium: "Medium", linkedin: "LinkedIn", tumblr: "Tumblr", news: "News" };
  return map[p] ?? p;
}

function buildEmailBody(summary: ProjectSummaryResponse, projectName: string) {
  const mentions = summary.mentions ?? [];
  const analyzed = mentions.filter((m) => m.sentimentStatus === "completed" && m.sentiment?.label);
  const posCount = analyzed.filter((m) => m.sentiment!.label!.toLowerCase() === "positive").length;
  const negCount = analyzed.filter((m) => m.sentiment!.label!.toLowerCase() === "negative").length;
  const neuCount = analyzed.length - posCount - negCount;
  const platformLines = (summary.byPlatform ?? []).map((p) => `- ${platformLabel(p.platform)}: ${p.count} mentions`).join("\n");

  return [
    `SentiMind report for ${projectName}`,
    "",
    `Total mentions: ${summary.totalMentions}`,
    `Analyzed: ${analyzed.length}`,
    `Positive: ${posCount}`,
    `Negative: ${negCount}`,
    `Neutral: ${neuCount}`,
    "",
    "Platform breakdown:",
    platformLines || "- No platform data available",
    "",
    "Generated by SentiMind.",
  ].join("\n");
}

export function ReportsView({ summary, project, loading, activeReport }: Props) {
  const [emailTo, setEmailTo] = useState("");
  const [emailSubject, setEmailSubject] = useState(`SentiMind Report: ${project?.primaryKeyword ?? "Project"}`);
  const [emailSent, setEmailSent] = useState(false);
  const [generating, setGenerating] = useState(false);
  const infographicRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setEmailSubject(`SentiMind Report: ${project?.primaryKeyword ?? "Project"}`);
  }, [project?.primaryKeyword]);

  const mentions = summary?.mentions ?? [];
  const analyzed = mentions.filter((m) => m.sentimentStatus === "completed" && m.sentiment?.label);
  const posCount = analyzed.filter((m) => m.sentiment!.label!.toLowerCase() === "positive").length;
  const negCount = analyzed.filter((m) => m.sentiment!.label!.toLowerCase() === "negative").length;
  const neuCount = analyzed.length - posCount - negCount;

  const handlePDF = useCallback(async () => {
    if (!summary) return;
    setGenerating(true);
    try {
      const doc = new jsPDF();
      const kw = project?.primaryKeyword ?? "Project";
      // Title
      doc.setFontSize(22);
      doc.setTextColor(6, 182, 212);
      doc.text("SentiMind Report", 20, 25);
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 33);
      doc.setFontSize(16);
      doc.setTextColor(30, 30, 30);
      doc.text(`Keyword: ${kw}`, 20, 45);

      // Summary stats
      doc.setFontSize(14);
      doc.setTextColor(6, 182, 212);
      doc.text("Overview", 20, 60);
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      doc.text(`Total Mentions: ${summary.totalMentions}`, 20, 70);
      doc.text(`Analyzed: ${analyzed.length}`, 20, 78);
      doc.text(`Positive: ${posCount} (${analyzed.length ? ((posCount / analyzed.length) * 100).toFixed(1) : 0}%)`, 20, 86);
      doc.text(`Negative: ${negCount} (${analyzed.length ? ((negCount / analyzed.length) * 100).toFixed(1) : 0}%)`, 20, 94);
      doc.text(`Neutral: ${neuCount} (${analyzed.length ? ((neuCount / analyzed.length) * 100).toFixed(1) : 0}%)`, 20, 102);

      // Platform breakdown
      doc.setFontSize(14);
      doc.setTextColor(6, 182, 212);
      doc.text("Platform Breakdown", 20, 118);
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      let y = 128;
      for (const p of summary.byPlatform ?? []) {
        doc.text(`${platformLabel(p.platform)}: ${p.count} mentions`, 20, y);
        y += 8;
      }

      // Recent mentions
      doc.setFontSize(14);
      doc.setTextColor(6, 182, 212);
      y += 6;
      doc.text("Recent Mentions (Top 15)", 20, y);
      y += 10;
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      for (const m of mentions.slice(0, 15)) {
        const text = (m.content || m.metadata?.title || "No content").slice(0, 80);
        const label = m.sentiment?.label ?? "pending";
        doc.text(`[${platformLabel(m.platform)}] [${label}] ${text}`, 20, y, { maxWidth: 170 });
        y += 7;
        if (y > 280) { doc.addPage(); y = 20; }
      }

      doc.save(`sentimind-report-${kw.replace(/\s+/g, "_")}.pdf`);
    } finally {
      setGenerating(false);
    }
  }, [summary, project, analyzed, mentions, posCount, negCount, neuCount]);

  const handleExcel = useCallback(() => {
    if (!summary) return;
    setGenerating(true);
    try {
      const wb = XLSX.utils.book_new();

      // Summary sheet
      const summaryData = [
        ["SentiMind Report", ""],
        ["Keyword", project?.primaryKeyword ?? ""],
        ["Generated", new Date().toLocaleString()],
        ["Total Mentions", summary.totalMentions],
        ["Analyzed", analyzed.length],
        ["Positive", posCount],
        ["Negative", negCount],
        ["Neutral", neuCount],
      ];
      const ws1 = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(wb, ws1, "Summary");

      // Platform sheet
      const platData = [["Platform", "Mentions"], ...(summary.byPlatform ?? []).map((p) => [platformLabel(p.platform), p.count])];
      const ws2 = XLSX.utils.aoa_to_sheet(platData);
      XLSX.utils.book_append_sheet(wb, ws2, "Platforms");

      // Mentions sheet
      const mentionRows = mentions.map((m) => [
        platformLabel(m.platform), m.author ?? "", (m.content ?? "").slice(0, 200),
        m.sentiment?.label ?? "pending", m.sentiment?.final_score?.toFixed(3) ?? "", m.sourceUrl ?? "",
        new Date(m.publishedAt).toLocaleDateString(),
      ]);
      const ws3 = XLSX.utils.aoa_to_sheet([["Platform", "Author", "Content", "Sentiment", "Score", "URL", "Date"], ...mentionRows]);
      XLSX.utils.book_append_sheet(wb, ws3, "Mentions");

      XLSX.writeFile(wb, `sentimind-report-${(project?.primaryKeyword ?? "project").replace(/\s+/g, "_")}.xlsx`);
    } finally {
      setGenerating(false);
    }
  }, [summary, project, analyzed, mentions, posCount, negCount, neuCount]);

  const handleEmailSend = useCallback(() => {
    if (!emailTo || !summary) return;
    setGenerating(true);
    const projectName = project?.primaryKeyword ?? "Project";
    const body = buildEmailBody(summary, projectName);
    const mailtoUrl = `mailto:${encodeURIComponent(emailTo.trim())}?subject=${encodeURIComponent(emailSubject.trim() || `SentiMind Report: ${projectName}`)}&body=${encodeURIComponent(body)}`;

    try {
      window.location.href = mailtoUrl;
      setEmailSent(true);
    } finally {
      setGenerating(false);
      setTimeout(() => setEmailSent(false), 3000);
    }
  }, [emailTo, summary, project, emailSubject]);

  const handleInfographic = useCallback(async () => {
    if (!infographicRef.current) return;
    setGenerating(true);
    try {
      const { default: html2canvas } = await import("html2canvas");
      const canvas = await html2canvas(infographicRef.current, { backgroundColor: "#0a0e1a", scale: 2 });
      const link = document.createElement("a");
      link.download = `sentimind-infographic-${(project?.primaryKeyword ?? "project").replace(/\s+/g, "_")}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (error) {
      console.error("Failed to generate infographic:", error);
    } finally {
      setGenerating(false);
    }
  }, [project]);

  if (loading) {
    return (
      <div className="rounded-2xl border border-border/60 bg-card/80 backdrop-blur-xl p-12 text-center">
        <div className="inline-flex items-center gap-2 text-sm text-muted-foreground"><div className="h-2 w-2 rounded-full bg-primary animate-pulse" /> Loading…</div>
      </div>
    );
  }

  if (!summary || mentions.length === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-border bg-card/80 backdrop-blur-xl p-12 text-center">
        <FileText className="h-10 w-10 text-primary mx-auto mb-3 opacity-60" />
        <p className="text-foreground font-semibold">No data for reports</p>
        <p className="text-sm text-muted-foreground mt-1">Run a collection first.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {activeReport === "email-reports" && (
        <div className="rounded-2xl border border-border/60 bg-card/80 backdrop-blur-xl p-6 shadow-neon">
          <h3 className="text-lg font-bold text-foreground mb-1 flex items-center gap-2"><Mail className="h-5 w-5 text-primary" /> Email Report</h3>
          <p className="text-sm text-muted-foreground mb-6">Send a formatted sentiment analysis report via email.</p>
          <div className="space-y-4 max-w-lg">
            <div>
              <label className="block text-xs font-bold uppercase tracking-widest text-muted-foreground mb-2">Recipient Email</label>
              <input type="email" value={emailTo} onChange={(e) => setEmailTo(e.target.value)} placeholder="name@example.com" className="w-full rounded-lg border border-border/60 bg-card/50 px-4 py-3 text-sm text-foreground placeholder-muted-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 transition" />
            </div>
            <div>
              <label className="block text-xs font-bold uppercase tracking-widest text-muted-foreground mb-2">Subject</label>
              <input type="text" value={emailSubject} onChange={(e) => setEmailSubject(e.target.value)} className="w-full rounded-lg border border-border/60 bg-card/50 px-4 py-3 text-sm text-foreground placeholder-muted-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 transition" />
            </div>
            <div className="rounded-lg border border-border/40 bg-muted/30 p-4">
              <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-2">Report Preview</p>
              <div className="text-sm text-foreground space-y-1">
                <p><strong>Keyword:</strong> {project?.primaryKeyword}</p>
                <p><strong>Total Mentions:</strong> {summary.totalMentions}</p>
                <p><strong>Sentiment:</strong> {posCount} positive, {negCount} negative, {neuCount} neutral</p>
                <p><strong>Platforms:</strong> {(summary.byPlatform ?? []).map((p) => platformLabel(p.platform)).join(", ")}</p>
              </div>
            </div>
            <button onClick={handleEmailSend} disabled={!emailTo || generating} className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-neon hover:shadow-neon-lg hover:scale-105 transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed">
              {emailSent ? <><Check className="h-4 w-4" /> Sent!</> : generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Sending…</> : <><Send className="h-4 w-4" /> Send Report</>}
            </button>
          </div>
        </div>
      )}

      {activeReport === "pdf-report" && (
        <div className="rounded-2xl border border-border/60 bg-card/80 backdrop-blur-xl p-6 shadow-neon">
          <h3 className="text-lg font-bold text-foreground mb-1 flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /> PDF Report</h3>
          <p className="text-sm text-muted-foreground mb-6">Download a comprehensive PDF report with all analysis data.</p>
          <div className="rounded-lg border border-border/40 bg-muted/30 p-6 mb-6">
            <p className="text-sm font-semibold text-foreground mb-3">Report will include:</p>
            <ul className="text-sm text-muted-foreground space-y-2">
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> Overview statistics & sentiment breakdown</li>
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> Platform-by-platform breakdown</li>
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> Top 15 recent mentions with sentiment</li>
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> Generated timestamp & project info</li>
            </ul>
          </div>
          <button onClick={handlePDF} disabled={generating} className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-neon hover:shadow-neon-lg hover:scale-105 transition duration-300 disabled:opacity-50">
            {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</> : <><Download className="h-4 w-4" /> Download PDF</>}
          </button>
        </div>
      )}

      {activeReport === "excel-export" && (
        <div className="rounded-2xl border border-border/60 bg-card/80 backdrop-blur-xl p-6 shadow-neon">
          <h3 className="text-lg font-bold text-foreground mb-1 flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary" /> Excel Export</h3>
          <p className="text-sm text-muted-foreground mb-6">Export all data to Excel for custom analysis.</p>
          <div className="rounded-lg border border-border/40 bg-muted/30 p-6 mb-6">
            <p className="text-sm font-semibold text-foreground mb-3">Spreadsheet will contain:</p>
            <ul className="text-sm text-muted-foreground space-y-2">
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> <strong>Summary</strong> — Overview stats & sentiment counts</li>
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> <strong>Platforms</strong> — Mention count per platform</li>
              <li className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500" /> <strong>Mentions</strong> — All {mentions.length} mentions with sentiment, author, URL</li>
            </ul>
          </div>
          <button onClick={handleExcel} disabled={generating} className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-neon hover:shadow-neon-lg hover:scale-105 transition duration-300 disabled:opacity-50">
            {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</> : <><Download className="h-4 w-4" /> Download Excel</>}
          </button>
        </div>
      )}

      {activeReport === "infographic" && (
        <>
          <div className="rounded-2xl border border-border/60 bg-card/80 backdrop-blur-xl p-6 shadow-neon">
            <h3 className="text-lg font-bold text-foreground mb-1 flex items-center gap-2"><Palette className="h-5 w-5 text-primary" /> Infographic</h3>
            <p className="text-sm text-muted-foreground mb-4">Download a visual infographic image of your analysis.</p>
            <button onClick={handleInfographic} disabled={generating} className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-neon hover:shadow-neon-lg hover:scale-105 transition duration-300 disabled:opacity-50 mb-6">
              {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</> : <><Image className="h-4 w-4" /> Download as PNG</>}
            </button>
          </div>

          <div ref={infographicRef} className="rounded-2xl border border-border/60 overflow-hidden" style={{ background: "linear-gradient(135deg, #0a0e1a 0%, #111827 50%, #0a0e1a 100%)", color: "#e2e8f0", padding: "40px" }}>
            <div style={{ textAlign: "center", marginBottom: 32 }}>
              <h2 style={{ fontSize: 28, fontWeight: 800, background: "linear-gradient(90deg, #06b6d4, #8b5cf6)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>SentiMind Analysis</h2>
              <p style={{ fontSize: 14, color: "#94a3b8", marginTop: 4 }}>{project?.primaryKeyword ?? "Project"} • {new Date().toLocaleDateString()}</p>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16, marginBottom: 32 }}>
              {[
                { label: "Total Mentions", value: summary.totalMentions, color: "#06b6d4" },
                { label: "Positive", value: `${posCount} (${analyzed.length ? ((posCount / analyzed.length) * 100).toFixed(0) : 0}%)`, color: "#22c55e" },
                { label: "Negative", value: `${negCount} (${analyzed.length ? ((negCount / analyzed.length) * 100).toFixed(0) : 0}%)`, color: "#ef4444" },
              ].map((s) => (
                <div key={s.label} style={{ borderRadius: 12, border: `1px solid ${s.color}33`, padding: 20, textAlign: "center", background: `${s.color}10` }}>
                  <div style={{ fontSize: 28, fontWeight: 800, color: s.color }}>{s.value}</div>
                  <div style={{ fontSize: 12, color: "#94a3b8", marginTop: 4 }}>{s.label}</div>
                </div>
              ))}
            </div>

            <div style={{ marginBottom: 24 }}>
              <h3 style={{ fontSize: 14, fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>Platform Breakdown</h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
                {(summary.byPlatform ?? []).map((p) => (
                  <div key={p.platform} style={{ borderRadius: 8, border: "1px solid #1e293b", padding: 12, background: "#0f172a" }}>
                    <div style={{ fontSize: 18, fontWeight: 700, color: "#e2e8f0" }}>{p.count}</div>
                    <div style={{ fontSize: 11, color: "#64748b" }}>{platformLabel(p.platform)}</div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{ textAlign: "center", fontSize: 10, color: "#475569", paddingTop: 16, borderTop: "1px solid #1e293b" }}>
              Generated by SentiMind • {new Date().toLocaleString()}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
